# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b1ae8d0aad972ccd7322bcceaaceae667509799f35dc33d9cdea47ae8c55834b8bbe3e8cc8a5815f6b023d7a76a7b0bc28889b97c1749557a393dbbdc54555b

test:
  secret_key_base: a6ceb5dac724217eccc021f62bc8cd6f70849ce46e4ca6652f00faa4302416137b1a84f2115e2613c7340f88b1a1202e98a8f06b4b5a458656856793a9deb4cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
